version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"

conda:
  environment: docs/requirements.yaml

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py

