# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-23.1"
  jobs:
    post_create_environment:
      - mamba env update --name latest --file docs/requirements.yaml

sphinx:
  configuration: docs/conf.py
