name: openff-pympfit-docs
channels:
  - conda-forge
dependencies:
  # Base depends
  - python >=3.10,<3.13
  - pip

  # Core package dependencies
  - numpy
  - jinja2
  - pydantic >=1.10.17,<3
  - openff-utilities
  - openff-units >=0.2
  - openff-toolkit-base >=0.14
  - openff-recharge >=0.5.0
  - sqlalchemy
  - sqlite

  # Documentation dependencies
  - sphinx
  - furo
  - sphinx-design
  - sphinx-copybutton
  - myst-parser

  # Install package from repo root
  - pip:
    - -e ..

